// Approved Kingdom Core systems from the Kingdom Carries v4 roadmap.
// This is intentionally machine-readable so CI can catch accidental removals.
export const APPROVED_V4_SYSTEMS = {
  4: ['Smart Carry Orchestrator', 'carryPartiesV3.js'],
  5: ['Live Carry Party System', 'carryPartiesV3.js'],
  6: ['Dynamic Joinable Carries', 'carryPartiesV3.js'],
  7: ['Carry Demand Heatmap', 'platformV4Runtime.js'],
  8: ['Predicted Queue Times', 'platformV4Runtime.js'],
  14: ['Verified Service Time', 'platformV4Interactions.js'],
  15: ['Carrier Reputation', 'platformV4Interactions.js'],
  16: ['Carrier Commendations', 'platformV4Interactions.js'],
  18: ['Mission Lifecycle State Machine', 'carryPartiesV3.js'],
  19: ['Mission Recovery System', 'platformV4Complete.js'],
  20: ['Carry No-Show Reliability', 'platformV4Complete.js'],
  21: ['Kingdom Progression Engine', 'platformV4Runtime.js'],
  24: ['Houses 2.0 Standings', 'platformV4.js'],
  28: ['Quest Engine', 'platformV4Runtime.js'],
  31: ['Prestige', 'platformV4Interactions.js'],
  33: ['Royal Treasury Ledger', 'platformV4Complete.js'],
  34: ['Treasury Approval Workflow', 'platformV4Interactions.js'],
  35: ['Item Lending', 'platformV4Complete.js'],
  36: ['Marketplace', 'platformV4Interactions.js'],
  37: ['Marketplace Search', 'platformV4Complete.js'],
  38: ['Market Watchlists', 'platformV4Complete.js'],
  41: ['Application Workflow OS', 'applicationLinks.js'],
  42: ['Application Scoring', 'platformV4Complete.js'],
  45: ['Application Analytics', 'platformV4.js'],
  46: ['Staff Operations Center', 'platformV4Complete.js'],
  47: ['Unified Ticket Console', 'platformV4Complete.js'],
  48: ['Ticket Ownership', 'platformV4Complete.js'],
  49: ['Ticket SLA', 'platformV4Complete.js'],
  50: ['Ticket Escalation', 'platformV4Complete.js'],
  51: ['Ticket Summaries', 'platformV4Complete.js'],
  52: ['Full Audit Ledger', 'platformV4Complete.js'],
  53: ['Permission Drift Detection', 'securityV4.js'],
  54: ['Bot Authorization Firewall', 'security.js'],
  55: ['Webhook Registry', 'securityV4.js'],
  56: ['Security Risk Engine', 'securityV4.js'],
  57: ['Automatic Lockdown', 'securityV4.js'],
  61: ['Member Verification Intelligence', 'platformV4Complete.js'],
  63: ['Server Statistics', 'serverStatsVerification.js'],
  64: ['Real-Time Operations Dashboard', 'platformV4Complete.js'],
  65: ['Public Transparency Dashboard', 'platformV4Complete.js'],
  66: ['Carrier Command Dashboard', 'platformV4Complete.js'],
  67: ['Staff Command Dashboard', 'platformV4Complete.js'],
  68: ['Member Dashboard', 'platformV4Complete.js'],
  69: ['Notification Router', 'communityV4.js'],
  70: ['Smart Carry Notifications', 'communityV4.js'],
  71: ['Scheduled Events Engine', 'communityV4.js'],
  72: ['Event RSVP', 'communityV4.js'],
  73: ['Automatic Event Teams', 'communityV4.js'],
  74: ['Tournament Engine', 'communityV4.js'],
  75: ['Referral Quality System', 'platformV4Complete.js'],
  76: ['Mentor Network', 'communityV4.js'],
  77: ['Royal Archives', 'communityV4.js'],
  78: ['Build Advisor', 'communityV4.js'],
  79: ['Knowledge Search', 'communityV4.js'],
  80: ['Application Assistant', 'communityV4.js'],
  81: ['Ticket Assistant', 'communityV4.js'],
  82: ['Security Assistant', 'communityV4.js'],
  83: ['Event Story Generator', 'communityV4.js'],
  84: ['Kingdom Data Warehouse', 'externalInfraV4.js'],
  85: ['Analytics Engine', 'platformV4Runtime.js'],
  86: ['Retention Analytics', 'platformV4Complete.js'],
  87: ['Funnel Analytics', 'platformV4Runtime.js'],
  88: ['Demand Forecasting', 'platformV4Runtime.js'],
  89: ['Carrier Coverage Planning', 'platformV4Complete.js'],
  90: ['Feature Flags', 'platformV4.js'],
  91: ['Configuration Dashboard', 'platformV4Complete.js'],
  92: ['Workflow Engine', 'platformV4Complete.js'],
  93: ['Event Bus Architecture', 'platformV4Runtime.js'],
  94: ['PostgreSQL Persistence Adapter', 'externalInfraV4.js'],
  95: ['Redis Queue + Cache Layer', 'externalInfraV4.js'],
  96: ['Background Worker', 'externalInfraV4.js'],
  97: ['Internal API', 'platformApiV4.js'],
  98: ['Real-Time WebSocket Layer', 'platformApiV4.js'],
  99: ['Observability', 'platformV4.js'],
  100: ['Self Diagnostics', 'platformV4Interactions.js'],
  101: ['Automatic Repair', 'securityV4.js'],
  102: ['Configuration Versioning', 'platformV4.js'],
  103: ['Staging Environment Support', 'deploy-staging.js'],
  104: ['Automated Integration Tests', 'v4-selftest.js'],
  105: ['Runtime Permission Tests', 'platformV4Complete.js'],
  106: ['Server Digital Twin', 'securityV4.js'],
  107: ['Kingdom Core Control Plane', 'platformV4Complete.js'],
  108: ['Architecture Convergence', 'setup.js'],
  109: ['Kingdom Core Platform End-State', 'setup.js']
};

export const APPROVED_V4_NUMBERS = Object.keys(APPROVED_V4_SYSTEMS).map(Number).sort((a, b) => a - b);
